apiVersion: apps/v1
kind: Deployment
metadata:
  name: kyosk-app
  labels:
    app: kyosk-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kyosk-app
  template:
    metadata:
      labels:
        app: kyosk-app
    spec:
      containers:
        - name: kyosk-app
          image: kyosk-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /api/health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /api/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
