apiVersion: v1
kind: Service
metadata:
  name: kyosk-service
spec:
  type: NodePort  # Exposes the service on a port accessible locally
  selector:
    app: kyosk
  ports:
    - protocol: TCP
      port: 8080       # Service port
      targetPort: 8080 # Container port
      nodePort: 30007  # Exposed local port (Minikube-specific)
